.TH "MOJO\-REPL" "1"
.nh
.ad l
.SH "NAME"
mojo\-repl \[em] Launches the Mojo REPL.
.SH "SYNOPSIS"
\fBmojo repl\fR [\fIlldb\-options\fR]
.br
.SH "DESCRIPTION"
Launches a Mojo read\-evaluate\-print loop (REPL) environment, which provides interactive development in the terminal. You can also start the REPL by simply running `mojo`.

Any number of options and arguments may be specified on the command line. These are then forwarded to the underlying lldb tool, which runs the REPL.
.SH "OPTIONS"
.SS "Common options"
.sp
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Displays help information.
.RE
.sp
.SH "SEE ALSO"
\fBmojo\fR(1)
