.TH "MOJO\-DEMANGLE" "1"
.nh
.ad l
.SH "NAME"
mojo\-demangle \[em] Demangles the given name.
.SH "SYNOPSIS"
\fBmojo demangle\fR [\fIoptions\fR] \fIname\fR
.br
.SH "DESCRIPTION"
If the given name is a mangled Mojo symbol name, prints the demangled name. If no name is provided, one is read from standard input.
.SH "OPTIONS"
.SS "Common options"
.sp
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Displays help information.
.RE
.sp
.SH "SEE ALSO"
\fBmojo\fR(1)
