.TH "MOJO\-DEBUG" "1"
.nh
.ad l
.SH "NAME"
mojo\-debug \[em] Launches the LLDB debugger with support for debugging Mojo programs.
.SH "SYNOPSIS"
\fBmojo debug\fR [\fIdebug\-options\fR]
.br
.SH "DESCRIPTION"
Launches the LLDB debugger with support for debugging programs written in Mojo, as well as other standard languages like C and C++.
This feature is still experimental.
.SH "OPTIONS"
.SS "Common options"
.sp
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Displays help information.
.RE
.sp
.SH "SEE ALSO"
\fBmojo\fR(1)
